#!/bin/bash
# cd models_old
sdf2usd ./ycb_019_pitcher_base/model*.sdf ./ycb_019_pitcher_base/output.usda
sdf2usd ./ycb_061_foam_brick/model*.sdf ./ycb_061_foam_brick/output.usda
sdf2usd ./person_standing/model.sdf ./person_standing/output.usda
sdf2usd ./ycb_021_bleach_cleanser/model*.sdf ./ycb_021_bleach_cleanser/output.usda
sdf2usd ./ycb_062_dice/model*.sdf ./ycb_062_dice/output.usda
echo 5 done!
sdf2usd ./trofast/model*.sdf ./trofast/output.usda
sdf2usd ./ycb_022_windex_bottle/model*.sdf ./ycb_022_windex_bottle/output.usda
sdf2usd ./ycb_063-a_marbles/model*.sdf ./ycb_063-a_marbles/output.usda
sdf2usd ./trofast_knob/model*.sdf ./trofast_knob/output.usda
sdf2usd ./ycb_024_bowl/model*.sdf ./ycb_024_bowl/output.usda
sdf2usd ./ycb_063-b_marbles/model*.sdf ./ycb_063-b_marbles/output.usda
sdf2usd ./wrc_bin_black/model*.sdf ./wrc_bin_black/output.usda
sdf2usd ./ycb_025_mug/model*.sdf ./ycb_025_mug/output.usda
sdf2usd ./ycb_065-a_cups/model*.sdf ./ycb_065-a_cups/output.usda
sdf2usd ./wrc_bin_green/model*.sdf ./wrc_bin_green/output.usda
sdf2usd ./ycb_026_sponge/model*.sdf ./ycb_026_sponge/output.usda
sdf2usd ./ycb_065-b_cups/model*.sdf ./ycb_065-b_cups/output.usda
sdf2usd ./wrc_bookshelf/model*.sdf ./wrc_bookshelf/output.usda
sdf2usd ./ycb_027_skillet/model*.sdf ./ycb_027_skillet/output.usda
sdf2usd ./ycb_065-c_cups/model*.sdf ./ycb_065-c_cups/output.usda
sdf2usd ./wrc_container_a/model*.sdf ./wrc_container_a/output.usda
sdf2usd ./ycb_028_skillet_lid/model*.sdf ./ycb_028_skillet_lid/output.usda
sdf2usd ./ycb_065-d_cups/model*.sdf ./ycb_065-d_cups/output.usda
sdf2usd ./wrc_container_b/model*.sdf ./wrc_container_b/output.usda
sdf2usd ./ycb_029_plate/model*.sdf ./ycb_029_plate/output.usda
sdf2usd ./ycb_065-e_cups/model*.sdf ./ycb_065-e_cups/output.usda
sdf2usd ./wrc_frame/model*.sdf ./wrc_frame/output.usda
sdf2usd ./ycb_030_fork/model*.sdf ./ycb_030_fork/output.usda
sdf2usd ./ycb_065-f_cups/model*.sdf ./ycb_065-f_cups/output.usda
sdf2usd ./wrc_ground_plane/model*.sdf ./wrc_ground_plane/output.usda
sdf2usd ./ycb_031_spoon/model*.sdf ./ycb_031_spoon/output.usda
sdf2usd ./ycb_065-g_cups/model*.sdf ./ycb_065-g_cups/output.usda
sdf2usd ./wrc_long_table/model*.sdf ./wrc_long_table/output.usda
sdf2usd ./ycb_032_knife/model*.sdf ./ycb_032_knife/output.usda
sdf2usd ./ycb_065-h_cups/model*.sdf ./ycb_065-h_cups/output.usda
sdf2usd ./wrc_stair_like_drawer/model*.sdf ./wrc_stair_like_drawer/output.usda
sdf2usd ./ycb_033_spatula/model*.sdf ./ycb_033_spatula/output.usda
sdf2usd ./ycb_065-i_cups/model*.sdf ./ycb_065-i_cups/output.usda
sdf2usd ./wrc_tall_table/model*.sdf ./wrc_tall_table/output.usda
sdf2usd ./ycb_035_power_drill/model*.sdf ./ycb_035_power_drill/output.usda
sdf2usd ./ycb_065-j_cups/model*.sdf ./ycb_065-j_cups/output.usda
sdf2usd ./wrc_tray/model*.sdf ./wrc_tray/output.usda
sdf2usd ./ycb_036_wood_block/model*.sdf ./ycb_036_wood_block/output.usda
sdf2usd ./ycb_070-a_colored_wood_blocks/model*.sdf ./ycb_070-a_colored_wood_blocks/output.usda
sdf2usd ./ycb_002_master_chef_can/model*.sdf ./ycb_002_master_chef_can/output.usda
sdf2usd ./ycb_037_scissors/model*.sdf ./ycb_037_scissors/output.usda
sdf2usd ./ycb_070-b_colored_wood_blocks/model*.sdf ./ycb_070-b_colored_wood_blocks/output.usda
sdf2usd ./ycb_003_cracker_box/model*sdf ./ycb_003_cracker_box/output.usda
sdf2usd ./ycb_038_padlock/model*.sdf ./ycb_038_padlock/output.usda
sdf2usd ./ycb_071_nine_hole_peg_test/model*.sdf ./ycb_071_nine_hole_peg_test/output.usda
sdf2usd ./ycb_004_sugar_box/model*.sdf ./ycb_004_sugar_box/output.usda
sdf2usd ./ycb_040_large_marker/model*.sdf ./ycb_040_large_marker/output.usda
sdf2usd ./ycb_072-a_toy_airplane/model*.sdf ./ycb_072-a_toy_airplane/output.usda
sdf2usd ./ycb_005_tomato_soup_can/model*.sdf ./ycb_005_tomato_soup_can/output.usda
sdf2usd ./ycb_042_adjustable_wrench/model*.sdf ./ycb_042_adjustable_wrench/output.usda
sdf2usd ./ycb_072-b_toy_airplane/model*.sdf ./ycb_072-b_toy_airplane/output.usda
sdf2usd ./ycb_006_mustard_bottle/model*.sdf ./ycb_006_mustard_bottle/output.usda
sdf2usd ./ycb_043_phillips_screwdriver/model*.sdf ./ycb_043_phillips_screwdriver/output.usda
sdf2usd ./ycb_072-c_toy_airplane/model*.sdf ./ycb_072-c_toy_airplane/output.usda
sdf2usd ./ycb_007_tuna_fish_can/model*.sdf ./ycb_007_tuna_fish_can/output.usda
sdf2usd ./ycb_044_flat_screwdriver/model*.sdf ./ycb_044_flat_screwdriver/output.usda
sdf2usd ./ycb_072-d_toy_airplane/model*.sdf ./ycb_072-d_toy_airplane/output.usda
sdf2usd ./ycb_008_pudding_box/model*.sdf ./ycb_008_pudding_box/output.usda
sdf2usd ./ycb_048_hammer/model*.sdf ./ycb_048_hammer/output.usda
sdf2usd ./ycb_072-e_toy_airplane/model*.sdf ./ycb_072-e_toy_airplane/output.usda
sdf2usd ./ycb_009_gelatin_box/model*.sdf ./ycb_009_gelatin_box/output.usda
sdf2usd ./ycb_050_medium_clamp/model*.sdf ./ycb_050_medium_clamp/output.usda
sdf2usd ./ycb_073-a_lego_duplo/model*.sdf ./ycb_073-a_lego_duplo/output.usda
sdf2usd ./ycb_010_potted_meat_can/model*.sdf ./ycb_010_potted_meat_can/output.usda
sdf2usd ./ycb_051_large_clamp/model*.sdf ./ycb_051_large_clamp/output.usda
sdf2usd ./ycb_073-b_lego_duplo/model*.sdf ./ycb_073-b_lego_duplo/output.usda
sdf2usd ./ycb_011_banana/model*.sdf ./ycb_011_banana/output.usda
sdf2usd ./ycb_052_extra_large_clamp/model*.sdf ./ycb_052_extra_large_clamp/output.usda
sdf2usd ./ycb_073-c_lego_duplo/model*.sdf ./ycb_073-c_lego_duplo/output.usda
sdf2usd ./ycb_012_strawberry/model*.sdf ./ycb_012_strawberry/output.usda
sdf2usd ./ycb_053_mini_soccer_ball/model*.sdf ./ycb_053_mini_soccer_ball/output.usda
sdf2usd ./ycb_073-d_lego_duplo/model*.sdf ./ycb_073-d_lego_duplo/output.usda
sdf2usd ./ycb_013_apple/model*.sdf ./ycb_013_apple/output.usda
sdf2usd ./ycb_054_softball/model*.sdf ./ycb_054_softball/output.usda
sdf2usd ./ycb_073-e_lego_duplo/model*.sdf ./ycb_073-e_lego_duplo/output.usda
sdf2usd ./ycb_014_lemon/model*.sdf ./ycb_014_lemon/output.usda
sdf2usd ./ycb_055_baseball/model*.sdf ./ycb_055_baseball/output.usda
sdf2usd ./ycb_073-f_lego_duplo/model*.sdf ./ycb_073-f_lego_duplo/output.usda
sdf2usd ./ycb_015_peach/model*.sdf ./ycb_015_peach/output.usda
sdf2usd ./ycb_056_tennis_ball/model*.sdf ./ycb_056_tennis_ball/output.usda
sdf2usd ./ycb_073-g_lego_duplo/mode*.sdf ./ycb_073-g_lego_duplo/output.usda
sdf2usd ./ycb_016_pear/model*.sdf ./ycb_016_pear/output.usda
sdf2usd ./ycb_057_racquetball/model*sdf ./ycb_057_racquetball/output.usda
sdf2usd ./ycb_077_rubiks_cube/model*.sdf ./ycb_077_rubiks_cube/output.usda
sdf2usd ./ycb_017_orange/model*.sdf ./ycb_017_orange/output.usda
sdf2usd ./ycb_058_golf_ball/model*.sdf ./ycb_058_golf_ball/output.usda
sdf2usd ./ycb_018_plum/model*.sdf ./ycb_018_plum/output.usda
sdf2usd ./ycb_059_chain/model*.sdf ./ycb_059_chain/output.usda
