version: '3.3'
services:
  nvidia:
    entrypoint:
      - ./runapp.sh
    environment:
      ACCEPT_EULA: Y
      DISPLAY: unix${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    network_mode: host
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '/etc/localtime:/etc/localtime:ro'
      - '$PWD/robots:/isaac_hsr/robots'
      - '$PWD/usd:/isaac_hsr/usd'
    image: 'nvcr.io/nvidia/isaac-sim:2021.2.1'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


